---
- name: Create new post
  hosts: localhost
  remote_user: root
  gather_facts: yes
  connection: ssh
  pre_tasks:
    - name: Initialize jekyll project name
      set_fact:
        jekyll_project_path: /home/ubuntu/myexam
      when: jekyll_project_path is not defined

    - name: Verify proj_env
      fail:
        msg: "Variable proj_env should be defined. Exiting."
      when: proj_env is not defined
  tasks:
    - include_role:
        name: jekyll
        tasks_from: add_post
      vars:
        post_date: "{{ ansible_date_time.date }}"
      when: proj_env == "dev"

    - name: Set bump_increment
      set_fact:
        bump_increment: bugfix
      when: proj_env == "dev"

    - name: Set bump_increment
      set_fact:
        bump_increment: minor
      when: proj_env == "staging"

    - include_role:
        name: jekyll
        tasks_from: bump_version
      vars:
        increment: "{{ bump_increment }}"
