---
- name: Create new post
  hosts: localhost
  remote_user: root
  # become_method: sudo
  gather_facts: yes
  connection: ssh
  pre_tasks:
    - name: Verify jekyll_project_path
      fail:
        msg: "Variable jekyll_project_path should be defined. Exiting."
      when: jekyll_project_path is not defined
  tasks:
    - include_role:
        name: jekyll
        tasks_from: add_post
      vars:
         post_date: "{{ ansible_date_time.date }}"
         jekyll_project_path: "{{ jekyll_project_path }}"
    - include_role:
        name: jekyll
        tasks_from: bump_version
      vars:
         increment: bugfix
         jekyll_project_path: "{{ jekyll_project_path }}"
