---
- name: Create new post
  hosts: localhost
  remote_user: root
  gather_facts: yes
  connection: ssh
  pre_tasks:
    - name: Initialize jekyll project name
      set_fact:
        jekyll_project_name: "lovenfrancist.github.io"

  tasks:
    - include_role:
        name: jekyll
        tasks_from: test_task
      vars:
        post_date: "{{ ansible_date_time.date }}"
