---
- name: Create new post
  template:
    src: post.yaml.j2
    dest: "{{ jekyll_project_path }}/_posts/{{ ansible_date_time.date }}-{{ post_title }}.markdown"
  vars:
    post_date: "{{ post_date }}"
    post_title: "{{ post_title }}"
    post_body: "{{ post_body_out.stdout }}"
