---
- name: Generate content
  command: /usr/games/fortune
  register: post_body_out
  # ignore_errors: true

- name: Initialize post_body_out, jekyll_project_path variables
  set_fact:
    post_title: "{{ post_body_out.stdout[:25].strip() }}"
    jekyll_project_path: "{{ playbook_dir.split('/')[0:-1]|join('/') }}/{{ jekyll_project_name | string }}"

- name: Create new post
  template:
    src: post.yaml.j2
    dest: "{{ jekyll_project_path }}/_posts/{{ ansible_date_time.date }}-{{ post_title }}.markdown"
  vars:
    post_date: "{{ post_date }}"
    post_title: "{{ post_title }}"
    post_body: "{{ post_body_out.stdout }}"
